# Generated by Django 4.2 on 2024-03-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("income_name", models.CharField(max_length=100)),
                ("income_amount", models.IntegerField()),
                ("income_category", models.CharField(max_length=50)),
                ("income_date", models.DateField(auto_now=True)),
            ],
        ),
    ]
